packages:
  # include packages in sub-folders (e.g. apps/ and packages/)
  - 'apps/**'
  - 'packages/**'
  # if required, exclude directories
  - '!**/test/**'
allowBuilds:
  '@tsparticles/engine': true
  sharp: true
  unrs-resolver: true
